Refactor deploy script for extensions
duckdb/duckdb pull request #10063
Opened 2023-12-22 15:06 UTC by samansmink

This PR does a small refactor with as a goal:

- deduplicate the `.github/workflows/_extension_deploy.yml` that we currently have duplicated across all out-of-tree extensions
- deduplicate the `scripts/extension-upload-single.sh` that we currently have duplicated across all out-of-tree extensions
- unify the script we use to deploy out of tree extensions to nightly and the production ones in the this repo
- remove some unused stuff i came across

Maybe @carlopi can chime in here on the WASM part here?

A note on the deduplication of the two files: we can only use those from within the duckdb organisation because we need to pass secrets into them. 3rd party will still need to copy the scripts

2023-12-25 09:43 UTC, carlopi requested changes
There is a change needed (error initially introduced by me that keeps popping up), but the rest looks solid.

Thanks

2023-12-25 09:43 UTC, carlopi commented on scripts/extension-upload-single.sh
> +  brotli < $ext.append > "$ext.compressed"
```suggestion
  brotli < $ext.append > "$ext.compressed"
else
  gzip < $ext.append > "$ext.compressed"
```

2024-01-02 09:18 UTC, samansmink commented on scripts/extension-upload-single.sh
> +  brotli < $ext.append > "$ext.compressed"
oops, good catch!

2024-01-02 09:19 UTC, samansmink commented
@Mytherin I think this is good to go, CI doesn't really do much for this PR

2024-01-02 09:20 UTC, djouallah commented
@samansmink can you please update the iceberg extension :)

2024-01-02 09:21 UTC, merged