Map creation fixes and refactoring
duckdb/duckdb pull request #10436
Opened 2024-02-02 09:52 UTC by taniabogatsch

This PR refactors the `MAP` creation code in `map.cpp`. It removes almost all special cases and uses selection vectors and our unified vector format for more uniform code paths.

2024-02-07 12:35 UTC, Tishj commented on src/core_functions/scalar/map/map.cpp
> +		if (!keys_data.validity.RowIsValid(keys_idx)) {
values_data, values_idx

2024-02-07 12:49 UTC, Tishj requested changes
Thanks, looks much cleaner this way!

I saw one issue, other than that it looks good to me :)

2024-02-07 12:59 UTC, taniabogatsch commented on src/core_functions/scalar/map/map.cpp
> +		if (!keys_data.validity.RowIsValid(keys_idx)) {
Oh, nice catch! Definitely!

2024-02-19 13:49 UTC, merged

2024-02-19 13:49 UTC, Mytherin commented
Thanks! LGTM