Simplify binary-search in FindRunIndex
duckdb/duckdb pull request #10487
Opened 2024-02-06 18:24 UTC by felipecrv

This is my first PR to DuckDB: it contains a simplification of the binary search in `arrow_conversion.cpp` — I don't have any reason to believe the original version has bugs, but the new implementation is easier to analyze.

I tested it with `BUILD_PYTHON=1 make -C build/debug install && pytest ./tools/pythonpkg/tests/fast/arrow/test_arrow_run_end_encoding.py`

2024-02-06 19:11 UTC, pdet commented
Valeu pela contribuição, Felipe! :-)

@szarnyasg Since that's @Tishj 's code, I think he can provide a more in-depth review, so I changed the review request to him if that's ok!

2024-02-06 19:35 UTC, Tishj commented on src/function/table/arrow_conversion.cpp
> +		// begin < end impies middle < end
implies*

2024-02-06 19:35 UTC, Tishj commented on src/function/table/arrow_conversion.cpp
> +			// run_ends[middle] > offset, so keep searching in [begin, middle)
>=

2024-02-06 19:40 UTC, Tishj requested changes
Thanks, just left some comments on the comments

2024-02-06 22:05 UTC, felipecrv commented on src/function/table/arrow_conversion.cpp
> +			// run_ends[middle] > offset, so keep searching in [begin, middle)
Sure.

2024-02-07 12:15 UTC, Tishj approved these changes
Thanks, looks much simpler 👍

2024-02-09 17:07 UTC, merged