Fix OrderPreservationType issue of MATERIALIZED CTEs
duckdb/duckdb pull request #10587
Opened 2024-02-12 09:56 UTC by kryonix

Materialized CTEs did sometimes not create the correct `OrderPreservationType`. This is because `OrderPreservationRecursive` tried to take the materialization phase into account, which should not be done.

Fixes https://github.com/duckdb/duckdb/pull/10576, reverts and fixes https://github.com/duckdb/duckdb/pull/10560.

The tests will likely fail, however, because this revealed another—unrelated—bug:

`test/sql/function/list/list_reverse.test`

```
WITH example AS (
  SELECT [1, 2, 3] AS arr UNION ALL
  SELECT [4, 5] AS arr UNION ALL
  SELECT [] AS arr
)
SELECT
  list_reverse(arr) AS reverse_arr
FROM example ORDER BY length(reverse_arr) DESC;
```

```
Invalid Error: Unoptimized statement differs from original result!
Original Result:
reverse_arr
INTEGER[]
[ Rows: 3]
[3, 2, 1]
[5, 4]
[]

Unoptimized:
reverse_arr
INTEGER[]
[ Rows: 3]
[1, 2, 3]
[4, 5]
[]
```

2024-02-12 15:07 UTC, kryonix commented
I did investigate the failing test case a bit further:

```
SELECT arr, list_concat(list_reverse(arr), arr) FROM (SELECT [1,2,3]) AS _(arr);
┌───────────┬─────────────────────────────────────┐
│ arr       ┆ list_concat(list_reverse(arr), arr) │
╞═══════════╪═════════════════════════════════════╡
│ [3, 2, 1] ┆ [1, 2, 3, 1, 2, 3]                  │
└───────────┴─────────────────────────────────────┘
```

This query contains _two_ bugs. First, column `arr` should be `[1,2,3]`, but it is reversed. This is a bug in `array_slice.cpp`, line 349: `ListVector::ReferenceEntry(result, list_or_str_vector);`. The input is just referenced, but I think the vector has to be copied. Otherwise, the input is changed.

https://github.com/duckdb/duckdb/pull/10587/commits/eeb0093a77d04a9499c0cf9c649928944369ef59 fixes the second bug, where `list_reverse` has no effect when nested in `list_concat`.

Again, this is totally unrelated to the initial issue I am trying to address with this pr.

2024-02-12 20:46 UTC, kryonix commented
Alright. I think I fixed it. However, I'm not sure if this fix of the array slicing code has a negative effect on performance due to copy overhead. It now copies the imput vector just as `list_sort` does.

2024-02-13 08:24 UTC, Mytherin approved these changes
Thanks for the fixes! LGTM. Perhaps @taniabogatsch can have a look at the changes to the list functions?

2024-02-13 11:05 UTC, taniabogatsch requested changes
Hi @kryonix, thanks for the PR and for uncovering these bugs! 

I think we need to look at them more in-depth before merging this. Especially for the second bug (`list_reverse` inside `list_concat`). I think the bug is not in the `list_concat` code, i.e., that code just receives incorrect input data.

Is it possible to merge these fixes without the changes to `list_concat`/`list_slice`? If so, I'd suggest that we open a separate issue/PR to address them separately?

2024-02-13 11:07 UTC, kryonix commented
> Is it possible to merge these fixes without the changes to list_concat/list_slice? If so, I'd suggest that we open a separate issue/PR to address them separately?

Yes it is. I only had a look at these issues because I introduced a new test case that does not work because of these bugs.

2024-02-13 11:15 UTC, kryonix commented on src/function/scalar/list/list_concat.cpp
> +			ListVector::Append(result, lhs_child, lhs_entry.offset + lhs_entry.length, lhs_entry.offset);
Feel free to revert this. I'm not too familiar with this part of the system. For my test cases (and the unit tests) it worked fine. But I may not see the whole picture.

2024-02-13 11:27 UTC, taniabogatsch commented
> Yes it is. I only had a look at these issues because I introduced a new test case that does not work because of these bugs.

Great - would it be okay for you to revert the changes here, and then we can merge this?

2024-02-13 11:42 UTC, kryonix commented on src/function/scalar/list/list_concat.cpp
> +			ListVector::Append(result, lhs_child, lhs_entry.offset + lhs_entry.length, lhs_entry.offset);
Awesome! I reverted the change.

2024-02-14 14:33 UTC, taniabogatsch approved these changes

2024-02-19 11:39 UTC, merged

2024-02-19 11:39 UTC, Mytherin commented
Thanks!