Join order optimizer asan bug refactor
duckdb/duckdb pull request #11794
Opened 2024-04-23 14:11 UTC by Tmonster

Follow up to https://github.com/duckdb/duckdb/pull/11719

This PR removes the JoinNode class completely. In addition, it removes a lot of other dead code that should have been removed a while ago. This solution passes a const reference to the dynamic programming table of plans to the query_graph_manager so that plan reconstruction can directly reference the dynamic programming table.  The reconstruction code can then lookup the left and right JoinRelationSets by looking into the DP table.

2024-04-24 14:22 UTC, lnkuiper requested changes
Looks great after the refactor! I just have two remarks, and then this is ready to go:

2024-04-24 14:22 UTC, lnkuiper commented on src/include/duckdb/optimizer/join_order/plan_enumerator.hpp
> +	//	unique_ptr<JoinNode> CreateJoinNodeFromDPJoinNode(DPJoinNode dp_node);
Should this comment be removed?

2024-04-24 14:22 UTC, lnkuiper commented on src/optimizer/join_order/plan_enumerator.cpp
> +	//	optional_ptr<reference_map_t<JoinRelationSet, unique_ptr<DPJoinNode>>> res = &plans;
Should this comment be removed?

2024-04-25 10:37 UTC, lnkuiper approved these changes
LGTM now, thanks!

2024-04-30 10:31 UTC, merged

2024-04-30 10:31 UTC, Mytherin commented
Thanks!