BUGFix Introducing Introducing Delim Joins and Denim gets should respect positionally
duckdb/duckdb pull request #11812
Opened 2024-04-24 12:54 UTC by Tmonster

fixes https://github.com/duckdblabs/duckdb-internal/issues/1807

In queries where a correlated subquery requires a delim get, we want to preserve positionally of columns. Operators can get moved around and when operators get moved around the positionally of columns can change. This is especially bad when you have set operations, where positionally is important. 

A delim_get is introduced with a cross product. The children of a cross product can be flipped around by the join order optimizer, affecting the positionally of the columns. With this fix, if a projecition wants to introduce a delim get, the delim get cross product is produced under it.

2024-04-29 14:21 UTC, lnkuiper requested changes
Looks good! Just two minor comments:

2024-04-29 14:21 UTC, lnkuiper commented on test/optimizer/case_simplification.test
> +mode skip
Is the skip here intentional?

2024-04-29 14:21 UTC, lnkuiper commented on src/planner/subquery/flatten_dependent_join.cpp
> +	unique_ptr<LogicalDelimGet> delim_scan = nullptr;
nitpick: `unique_ptr` is initialized to `nullptr` by default

2024-04-29 14:43 UTC, lnkuiper approved these changes
LGTM now, thanks!

2024-04-30 10:31 UTC, merged

2024-04-30 10:31 UTC, Mytherin commented
Thanks!