Remove sqlsmith extension
duckdb/duckdb pull request #12300
Opened 2024-05-29 09:15 UTC by Tmonster

Removing the SQL Smith extension. Have a repo up here so the extension can go out of tree https://github.com/Tmonster/duckdb-sqlsmith . Before this gets merged, some other tasks need to happen, This PR is being opened to check CI

- [ ] Ownership of the duckdb-sqlsmith repo should move to duckdb
- [ ]  More fuzzer scripts should move to the sqlsmith repo.
- [ ]  CI workflows in https://github.com/duckdb/duckdb-fuzzer should be checked to make sure they work with sql-smith out of tree.
- [ ] More??

2024-05-31 12:26 UTC, Mytherin reviewed
Thanks for the PR! Great idea - LGTM. One minor comment

2024-05-31 12:26 UTC, Mytherin commented on src/include/duckdb/main/extension_entries.hpp
> -    {"fuzzyduck", "sqlsmith", CatalogType::TABLE_FUNCTION_ENTRY},
I think these shouldn't be removed

2024-06-03 12:04 UTC, carlopi commented on .github/config/out_of_tree_extensions.cmake
> +duckdb_extension_load(sqlsmith)
```suggestion
duckdb_extension_load(sqlsmith
```
I think like this it should work

2024-06-03 12:05 UTC, carlopi requested changes
Minor typo, plus I think duckdblabs/duckdb-fuzzer-ci should be moved from BUILD_SQLSMITH=1 to point to the now out of tree extension.

Unsure if there are other places (that we care about) that are using the BUILD_SQLSMITH=1 syntax.

2024-06-04 15:08 UTC, carlopi approved these changes
Cool, thanks.

Should this go into feature OR directly into main? I would not be opposed for this to go in main. Either way I think fuzzer should directly use duckdb/duckdb_sqlsmith, and same development should be made in the separate repo.

I realized something that had not seen before, we could BUILD_SQLSMITH=1 to append, at the Makefile level, sqlsmith.cmake to the list of cmake files that will get checked.

That would be the way to support migration for BUILD_X.
In the case of SQLSMITH is not super relevant, but other extensions are harder to separate.

2024-06-04 15:34 UTC, Tmonster commented
I'm also fine with this going into main, but given that main is currently being used to track v1.0.0 I don't think this should go in until all bug fix releases are out or v1.0.0 has it's own branch for future bug fixes

2024-06-05 06:33 UTC, merged

2024-06-05 06:33 UTC, Mytherin commented
Thanks!