[PySpark] - Allow union all by name
duckdb/duckdb pull request #12345
Opened 2024-06-01 14:33 UTC by mariotaddeucci

2024-06-01 16:54 UTC, Tishj commented on tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
> +                self = self.withColumn(
This is altering self which I don't think we want to do, this should be a "const" method with no side effects beyond the returned result

2024-06-01 16:57 UTC, Tishj commented on tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
> +            for col in set(self.columns) - set(other.columns):
I also wonder if this has side effects on the passed in `other`, I suspect it does
It shouldn't.

2024-06-01 18:57 UTC, mariotaddeucci commented
@Tishj fixed, no side effects

2024-06-03 08:25 UTC, Tishj requested changes
Thanks, could we add more tests?
- testing the `"Union by name requires the same number of columns"` error
- missing columns on the `self` side (allowMissingColumns)
- missing columns on the `other` side (allowMissingColumns)

2024-06-13 08:45 UTC, Tishj commented on tools/pythonpkg/tests/fast/spark/test_spark_union_by_name.py
> +        with pytest.raises(ValueError):
please use `match: ...` to check for an explicit error, ValueError is too generic

2024-09-20 16:17 UTC, mariotaddeucci commented
@Mytherin is there something to change?

2024-10-14 15:37 UTC, Mytherin commented
There's still some open comments from @Tishj, as well as a merge conflict. Could you have another look?

2024-10-19 04:41 UTC, closed without merging