feat: new inet functions
duckdb/duckdb pull request #12575
Opened 2024-06-17 21:09 UTC by panga

Currently, INET extension is missing functions for INET range operations, related issue https://github.com/duckdb/duckdb/issues/10947.  
However, this PR aims to add the subnet contains operations and other helper functions.

* Add missing `BUILD_INET` in `Makefile`.
* All new functions works with IPv4/IPv6 and contains tests.
* Add five new INET functions compatible with PostgreSQL (https://www.postgresql.org/docs/current/functions-net.html):

`netmask` Computes the network mask for the address's network.
```sql
netmask(inet '192.168.1.5/24') → 255.255.255.0
```

`network` Returns the network part of the address, zeroing out whatever is to the right of the netmask.
```sql
network(inet '192.168.1.5/24') → 192.168.1.0/24
```

`broadcast` Computes the broadcast address for the address's network.
```sql
broadcast(inet '192.168.1.5/24') → 192.168.1.255/24
```

`<<=` Is subnet contained by or equal to subnet?
```sql
inet '192.168.1.5/32' <<= inet '192.168.1.0/24' → true
```

`>>=` Does subnet contain or equal subnet?
```sql
inet '192.168.1.5/32' >>= inet '192.168.1.0/24' → false
```

Note: I'm not familiar with duckdb code and it is my first contribution.

2024-06-21 16:01 UTC, chrisiou requested changes
hey @panga, thanks a lot for opening this PR! Everything looks good.
Could you please include some non-happy path test cases like more complex scenarios or failure cases? 
To ensure comprehensive testing coverage and prevent issues from future changes, it'd be nice to cover the following scenarios across all the new functions such as:
- subnet mask scenarios:
    - a single host mask (`/32` for IPv4, `/128` for IPv6)
    - a subnet mask covering all addresses (`/0` for both IPv4 and IPv6)
    - invalid mask values (e.g. `NULL` input, or bigger number than 32)
- some edge cases:
    - `192.168.1.255/24` or `2001:0db8::/96`
    - `0.0.0.0/19` or `::42`
- invalid address input values or invalid mask lengths
    - `999.999.999.999/24`, the existence of characters or `NULL` values

To test unexpected/incorrect usage, you can use:
```
statement error
<statement>
----
<error_msg>
```

2024-06-24 13:21 UTC, panga commented on test/sql/inet/test_inet_functions.test
> +
The requested new test cases were added.

2024-06-24 13:21 UTC, panga commented on test/sql/inet/test_ipv6_inet_functions.test
Done.

2024-06-24 13:21 UTC, panga commented on test/sql/inet/test_inet_operations.test
> +# subset
Done.

2024-06-24 13:21 UTC, panga commented on test/sql/inet/test_ipv6_inet_operations.test
> +# subset
Done.

2024-06-24 13:23 UTC, panga commented
@chrisiou thank you so much for the review. I've added the requested test cases.
Please note the new functions rely on INET datatype and thus only operates on valid IP v4/v6.
You can find the type conversion tests with invalid ip/mask in the test_inet_type.test files.

2024-06-24 17:21 UTC, chrisiou approved these changes
Looks good to me, thank you @panga!

2024-07-02 15:34 UTC, merged

2024-07-02 15:34 UTC, Mytherin commented
Thanks!