ci: use `actions/checkout@v4` everywhere
duckdb/duckdb pull request #12656
Opened 2024-06-23 10:58 UTC by peter-gy

Fixes the deprecation warning:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

2024-06-23 11:51 UTC, carlopi requested changes
This has been proposed earlier (probably by @krlmlr), and it would be nice, BUT there are jobs where we force specific versions of GLIBC like https://github.com/duckdb/duckdb/actions/runs/9632899589/job/26566653355?pr=12656 and this fails.

General solution for these cases is possibly split checkout AND actual workflow in two separate steps, or move checkout above starting the container.

If you want to reduce the change set to avoid failures, or finding workarounds, this PR is welcome but should come without adding problems.

2024-06-23 12:00 UTC, carlopi commented
One thing I forgot but it's important: the PR is very welcome, there is plenty of chances to improve what we do, and this is a nice angle to reduce noise. So first a big "Thanks!!" that I forgot to include in my review.

If you can remove the changes whenever those trigger a "missing GLIBC" error, than it should be OK to be merged and those other places can be handled separately.

2024-06-24 17:45 UTC, peter-gy commented
> One thing I forgot but it's important: the PR is very welcome, there is plenty of chances to improve what we do, and this is a nice angle to reduce noise. So first a big "Thanks!!" that I forgot to include in my review.
> 
> If you can remove the changes whenever those trigger a "missing GLIBC" error, than it should be OK to be merged and those other places can be handled separately.

Thank you for the feedback!
Will look into it.

2024-08-26 06:33 UTC, carlopi commented
A version of this is ready to be merged here: https://github.com/duckdb/duckdb/pull/13393, so this can likely be closed.

Thanks for the contribution

2024-08-26 06:46 UTC, closed without merging