PySpark sort by columns and DataFrame.getitem
duckdb/duckdb pull request #12981
Opened 2024-07-13 17:40 UTC by khalidmammadov

Adds to PySpark API:
- sort by given columns
- getitem returns columns or DataFrame
- get attribute returns Column instead of duckdb.ColumnExpression

these changes are inline with PySpark API

2024-07-14 16:22 UTC, khalidmammadov commented
@Tishj can you please review?

2024-07-15 08:36 UTC, Tishj requested changes
Thanks for the PR, I left some minor comments

2024-07-15 19:19 UTC, khalidmammadov commented on tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
> +            raise TypeError("Argument `ascending` should be a bool or"
I thought API should be consistent with PySpark hence the copy. Will mention next time.
Below replaced above error class. Not sure if it's needed to implement those classes or not at this point. Perhaps bit later when most of the main functionality is done.
```
        else:
            raise TypeError("Argument `ascending` should be a bool or"
                            f" list, got {type(ascending).__name__}.")
```
The error text is take from Spark's errors metadata.

2024-07-16 21:31 UTC, khalidmammadov commented on tools/pythonpkg/duckdb/experimental/spark/sql/dataframe.py
> +            raise TypeError("Argument `ascending` should be a bool or"
Sorry, my bad. I didn't realise these classes have already been implemented. 
I have added them everywhere for sort method + test cases.

2024-07-17 09:29 UTC, Tishj approved these changes
Thanks for the contribution, greatly appreciated 👍

2024-07-18 19:14 UTC, merged

2024-07-18 19:14 UTC, Mytherin commented
Thanks!