remove sqlsmith patch
duckdb/duckdb pull request #13334
Opened 2024-08-07 06:46 UTC by Tmonster

Removing sqlsmith patch as it has been applied in 

https://github.com/duckdb/duckdb_sqlsmith/pull/19

2024-08-07 08:34 UTC, carlopi requested changes
I think you need to remove the APPLY_PATCHES line from `.github/config/out-of-tree.cmake` and same from the custom cmake in duckdblabs/duckdb-fuzzer-ci.

2024-08-07 17:15 UTC, carlopi commented on .github/config/out_of_tree_extensions.cmake
>          GIT_TAG 721460ff1f31ce1dc1e4a9c4a55c0faf0b466dcb
```suggestion
        GIT_TAG 9729cade201987b22ec7fc4b700f6d34e1e4111f
```
Forgot, also this needs to be bumped to AFTER absorbing the patches.

2024-08-07 17:16 UTC, carlopi commented
> Done. @carlopi , if there are no patches, does apply patches then fail the build?

Yes, if `APPLY_PATCHES` is present some patches need to available.

2024-08-08 11:47 UTC, Tmonster commented
I imagine the extension builds are failing because they attempt to build sqlsmith with patches

2024-08-09 12:15 UTC, merged

2024-08-09 12:15 UTC, Mytherin commented
Thanks!