Implement PullUp Empty Results optimizer
duckdb/duckdb pull request #13524
Opened 2024-08-23 08:56 UTC by Tmonster

Currently this logic is sprinkled within filter pull up and filter push down. The problem is it's not at every operator, and adding empty results across multiple files within the filter pullup/pushdown operator can make the code hard to maintain and debug. 

This will unify the code and fix some fuzzer issues that are the cause of long execution times on the LHS of a join while a child on the RHS is empty . It can also help make other queries faster in a few cases.

One con is that some `ConversionErrors` will be hidden.

2024-09-02 12:45 UTC, Tmonster commented
Main needs to be merged into feature, then the commit history should be cleaned up a little bit

2024-10-02 10:30 UTC, hannes commented
Can you fix the conflict please?

2024-10-02 12:19 UTC, lnkuiper requested changes
Thanks for the PR! This looks good, I just have some minor comments:

2024-10-02 12:19 UTC, lnkuiper commented on src/include/duckdb/optimizer/empty_result_pullup.hpp
> +//! The Deliminator optimizer traverses the logical operator tree and removes any redundant DelimGets/DelimJoins
Could you update this comment to describe this operator?

2024-10-02 12:19 UTC, lnkuiper commented on src/include/duckdb/optimizer/empty_result_pullup.hpp
> +	unique_ptr<LogicalOperator> PullUpEmptyJoinChildren(unique_ptr<LogicalOperator> op);
Could you make `PullUpEmptyJoinChildren` private?

2024-10-03 09:32 UTC, lnkuiper approved these changes
Thanks for the changes, LGTM!

2024-10-11 10:56 UTC, merged

2024-10-11 10:56 UTC, Mytherin commented
Thanks! Looks great