[Dev] Fix an issue causing ExecuteTask to do much more work than intended
duckdb/duckdb pull request #14034
Opened 2024-09-19 12:12 UTC by Tishj

This PR makes `ExecutePushInternal` respect the `max_chunks` set in the call to `PipelineExecutor::Execute(idx_t max_chunks)`

When running DuckDB inside an environment where the control over received signals (like SIGINT) is not instant (like Python or Postgres), we rely on ExecuteTask to return after doing a small amount of processing work.

In the DuckDB CLI this problem was not apparent because SIGINT is handled and `Interrupt()` is called instantly, which is respected by the execution.
This problem only appeared because the `interrupt` flag could not be set as the application was first waiting for ExecuteTask to return.

2024-09-19 12:15 UTC, Tishj commented
This is definitely out of my depth and I'm not confident all cases are considered or the necessary state in the PipelineExecutor is preserved to support pausing this process.

The original problem was that ExecutePushInternal would only return when the `Execute(chunk, chunk, idx_t)` call would not return HAVE_MORE_OUTPUT

2024-09-20 14:43 UTC, Tishj commented
`TryFlushCachingOperators` is not prepared to deal with `ExecutePushInternal` returning `HAVE_MORE_OUTPUT`, that's the main thing I see that still needs to be fixed

2024-09-23 12:45 UTC, Tishj commented
> `TryFlushCachingOperators` is not prepared to deal with `ExecutePushInternal` returning `HAVE_MORE_OUTPUT`, that's the main thing I see that still needs to be fixed

I fixed this by detecting that `HAVE_MORE_OUTPUT` gets returned from `ExecutePushInternal`, then returning `false` **without setting `remaining_sink_chunk`** to indicate that the flushing did not complete yet.

Outside of `TryFlushCachingOperator` we check if `remaining_sink_chunk` was set:
```c++
				if (remaining_sink_chunk) {
					return PipelineExecuteResult::INTERRUPTED;
				} else {
					return PipelineExecuteResult::NOT_FINISHED;
				}
```

By not setting `remaining_sink_chunk` we don't try to re-sink the chunk, enter TryFlushCachingOperators as normal, and because `in_process_operators` is non-empty (otherwise `HAVE_MORE_OUTPUT` would not be returned) we will get back into `ExecutePushInternal` where we continue pushing the produced chunks into the Sink.

2024-10-02 10:44 UTC, lnkuiper requested changes
Thanks for the PR! This looks great. I just want to add a few assertions:

2024-10-02 10:44 UTC, lnkuiper commented on src/include/duckdb/parallel/pipeline_executor.hpp
> +	}
Can we add this method here?
```c++
bool IsDepleted() const {
    return processed >= maximum_to_process;
}
```
And use it in the `Next()` function (and possibly some assertions as well?).

Also, should `processed` ever be greater than `maximum_to_process`? Maybe we should assert that it is less or equal in `IsDepleted`.

2024-10-02 10:44 UTC, lnkuiper commented on src/parallel/pipeline_executor.cpp
> +			// we need to continue this the next time Execute is called.
Can we assert that the chunk budget was depleted here using the method I proposed above? I'd like to be sure that this comment is correct

2024-10-07 07:32 UTC, lnkuiper approved these changes
Thanks for the changes! LGTM now

2024-10-07 07:42 UTC, merged

2024-10-07 07:42 UTC, Mytherin commented
Thanks!