Fix #14833: split_part follow pg
duckdb/duckdb pull request #14875
Opened 2024-11-18 12:54 UTC by flashmouse

This pr try to fix #14833

2024-11-19 09:50 UTC, taniabogatsch requested changes
Hi @flashmouse, thanks for the PR! Looks good; I've left two comments.

2024-11-19 09:50 UTC, taniabogatsch commented on src/catalog/default/default_functions.cpp
> +	{DEFAULT_SCHEMA, "split_part", {"string", "delimiter", "position", nullptr}, {{nullptr, nullptr}}, "if(string IS NOT NULL AND delimiter IS NOT NULL, coalesce(string_split(string, delimiter)[position
Postgres also returns `NULL`, if the position is `NULL`. Let's also align that: 
`if(string IS NOT NULL AND delimiter IS NOT NULL AND position IS NOT NULL, ...`


```sql
postgres=# select split_part('a,b,c','',null) is null;
 ?column? 
----------
 t
(1 row)
```

DuckDB
```sql
D select split_part('a,b,c','',null) is null;
┌─────────────────────────────────────────┐
│ (split_part('a,b,c', '', NULL) IS NULL) │
│                 boolean                 │
├─────────────────────────────────────────┤
│ false                                   │
└─────────────────────────────────────────┘
```

2024-11-19 09:50 UTC, taniabogatsch commented on test/sql/function/string/test_split_part.test
> +NULL
Let's add one more test for the 'position is `NULL`' case.

2024-11-19 12:11 UTC, taniabogatsch approved these changes

2024-11-20 09:59 UTC, merged

2024-11-20 09:59 UTC, Mytherin commented
Thanks!