[easy] [no-op] Minor optimization on iterator update
duckdb/duckdb pull request #15349
Opened 2024-12-15 12:35 UTC by dentiny

While reading the code, I found these places does double lookup in the set / map container, while we could save the second lookup by (1) store the returned iterator for `find`; (2) leverage the `emplace` API provided by the container.

Reference to `emplace` API, which returns the iterator and whether the item is new:
unordered set: https://en.cppreference.com/w/cpp/container/unordered_set/emplace
unorderdd map: https://en.cppreference.com/w/cpp/container/unordered_map/emplace

2024-12-15 20:49 UTC, carlopi requested changes
Thanks, this looks to make sense to me, it will also speed up some cases where double lookup or lookup + insert are slower than it should.

One thing, I will keep using insert `instead` of `emplace`, since they behave slightly different, and it's hard to prove for them to behave the same.

2024-12-15 20:49 UTC, carlopi commented on src/execution/column_binding_resolver.cpp
> +			const bool is_new = result.emplace(index).second;
```suggestion
			const bool is_new = result.insert(index).second;
```

2024-12-15 20:49 UTC, carlopi commented on src/execution/column_binding_resolver.cpp
> +		const bool is_new = result.emplace(index).second;
```suggestion
		const bool is_new = result.insert(index).second;
```

2024-12-15 20:49 UTC, carlopi commented on src/execution/operator/persistent/physical_update.cpp
> +		const auto is_new = g_state.updated_rows.emplace(row_id).second;
```suggestion
		const auto is_new = g_state.updated_rows.insert(row_id).second;
```

2024-12-15 23:04 UTC, dentiny commented on src/execution/column_binding_resolver.cpp
> +			const bool is_new = result.emplace(index).second;
Updated.

2024-12-15 23:05 UTC, dentiny commented on src/execution/column_binding_resolver.cpp
> +		const bool is_new = result.emplace(index).second;
Updated.

2024-12-15 23:06 UTC, dentiny commented on src/execution/operator/persistent/physical_update.cpp
> +		const auto is_new = g_state.updated_rows.emplace(row_id).second;
Updated.

2024-12-15 23:09 UTC, dentiny commented
> One thing, I will keep using insert `instead` of `emplace`, since they behave slightly different, and it's hard to prove for them to behave the same.

Not a C++ lawyer, looks like emplace vs insertion are implementation dependent:
- Stackoverflow discussion thread: https://stackoverflow.com/questions/26446352/what-is-the-difference-between-unordered-mapemplace-and-unordered-mapinsert

For this PR, I simply did some quick `git grep find(`, feel free to let me know if you have other valid cases I could help in the future :)

2024-12-16 05:24 UTC, carlopi commented
The problem are not that on performance (those are implementation dependent), but on semantics, there is a line in the comment you linked like:
> You need to be more careful you are passing the correct arguments to the emplacement functions.

That is since `emplace` takes same element as the constructor, while `insert` is more strict.
And given changing arguments might change code actually executed, I think it's better to keep the original behaviour.

2024-12-16 05:24 UTC, carlopi approved these changes
Thanks, nice to clean those up.

2024-12-16 05:34 UTC, dentiny commented
> That is since emplace takes same element as the constructor, while insert is more strict.
And given changing arguments might change code actually executed, I think it's better to keep the original behaviour.

Got it, thanks for explanation!

2024-12-16 09:34 UTC, Tishj commented
Thanks, but I really don't feel like we need these changes
Unless you can provide benchmarks to show how this improves performance, I don't think it's worth it
`insert(...).second` has a higher mental load than `find(...) != end()`

I don't think these are ever used in hot paths, and furthermore it looks like the double lookup work would only happen on debug builds, as that is the only place where assertions run

2024-12-17 13:10 UTC, hannes commented
I agree with @Tishj

2024-12-18 10:30 UTC, dentiny commented
Thanks all for the reply!

I made this PR for two purpose:
1. minor performance improvement
2. "better" usage for C++ (feel free to hold different opinions)

The only thing I did in this PR is to avoid double container lookup, and it could be theoretically verified less operation is involved.

Original code:
```
if (result.find(index) != result.end()) {  // one lookup
  // do something
}
result.insert(index);  // one lookup and write
```
Updated code:
```
const bool is_new = result.insert(index).second;
if (!is_new) {
  // do something
}
```

> Unless you can provide benchmarks to show how this improves performance, I don't think it's worth it

I ran some unit tests locally, unfortunately I don't see any performance difference. I think it's not so surprising,
- These iterator lookups happens in memory, compared with IO operations (which takes most of the time I guess), time spent on these operations relatively small;
- For (contiguous) container second lookup, likely it's hitting L1 d-cache and TLB-cache, so ignorable performance impact;
- As you mentioned, the code here doesn't sit at critical path, which reduces the performance impact again;
- That's why I use the wording "minor optimization" in the PR title :)

> To me personally, insert(...).second has a higher mental load than find(...) != end()
I'm honestly having trouble reviewing that this behaves the same

Well, hmm, I would say, it's more like a personal preference :sweat_smile: 
I personally think checking iterator and insertion success is intuitive.

C++ standards created these overloads, from my perspective, is to encourage people to select a "better" and "suitable" version in certain situations. I personally feel all the use cases in the PR is reasonable.  :sweat_smile: 

> Thanks, but I really don't feel like we need these changes

The main motivation to make these PRs is I'm that type of person, hoping to have "clean and better" usage of C++;
Mainly to make the codebase / duckdb a little better, even it's minor.

Well I could understand some of your concern here, the performance could be minor, not super useful;
Similar PRs actually adds your overhead to review and potential back-and-forth, etc.
I personally could guarantee I won't do similar things again in the future.
But, well, feel free to close the PR if you like :(

2025-01-02 10:02 UTC, Mytherin reviewed
Thanks for the PR!

I'm fine with these changes in the `string_value_scanner`, the `physical_update` and the `physical_drop` - the rest seem unnecessary to me. Performance is not really a concern when dealing with assertions/verification code. 

Could you revert the other changes and keep only those?

2025-01-02 10:26 UTC, dentiny commented
> Thanks for the PR!
> 
> I'm fine with these changes in the `string_value_scanner`, the `physical_update` and the `physical_drop` - the rest seem unnecessary to me. Performance is not really a concern when dealing with assertions/verification code.
> 
> Could you revert the other changes and keep only those?

Sure! All unnecessary changes are reverted. Thank you for the review and reply!

2025-01-03 05:34 UTC, dentiny commented
Unnecessary changes have been reverted and CI passes.

2025-08-11 09:09 UTC, merged