[Parquet] Option to not cache union readers
duckdb/duckdb pull request #15435
Opened 2024-12-21 02:24 UTC by thalassemia

I have a niche use case where I want to scan a large amount of Parquet files, each with very large schemas (hundreds of columns, long column names, many nested columns), with `union_by_name=True`. [The benchmark I added](https://github.com/thalassemia/duckdb/blob/2838e311550ed631d206f58c1a1a2cc5690bee82/benchmark/parquet/large_schema_union_by_name.benchmark) exemplifies this use case. Changing the run command to `repeat` 1,000,000 times, `main` used upwards of 40GB of RAM on my machine. Almost all of this is from caching of Parquet readers (including metadata/schema) when running with `union_by_name=True`. With this PR, even 1,000,000 repeats required less than 2GB of RAM to run.

I made this an opt-in feature because of the potential performance penalty from having to remake the readers. However, on fast local SSD storage, the benchmark I added is not significantly slower with my PR versus without.

2025-01-06 08:51 UTC, lnkuiper requested changes
Thanks for the PR! I have two comments:

2025-01-06 08:51 UTC, lnkuiper commented on benchmark/parquet/large_schema_union_by_name.benchmark
> +# name: benchmark/parquet/large_schema_union_by_name.benchmark
Can we add a test that tests the new parameter for CSV as well?

2025-01-06 08:51 UTC, lnkuiper commented on src/include/duckdb/common/union_by_name.hpp
> +			vector<vector<string>> union_col_names_per_thread(max_threads);
Would it be possible to unify the code paths for when the union readers are cached and aren't cached?

If we save the types and names in these vectors in both cases:
```c++
vector<vector<LogicalType>> union_col_types_per_thread(max_threads);
vector<vector<string>> union_col_names_per_thread(max_threads);
```
Could we handle the logic for caching/not caching the reader within the task?

Then we only have one code path, and adding more options down the line becomes easier. Have you already tried this or think it's not possible?

2025-01-08 08:03 UTC, thalassemia commented on benchmark/parquet/large_schema_union_by_name.benchmark
> +# name: benchmark/parquet/large_schema_union_by_name.benchmark
I got this PR working for CSVs as well. For testing, I added an existing `union_by_name` benchmark to the regression test suite and several tests for `cache_union_readers=False`.

2025-01-08 08:03 UTC, thalassemia commented on src/include/duckdb/common/union_by_name.hpp
> +			vector<vector<string>> union_col_names_per_thread(max_threads);
Thanks for the suggestion! I had not previously considered this and implementing it yielded much cleaner code.

2025-01-08 08:07 UTC, thalassemia commented
The CI failure in `test/sql/catalog/dependencies/test_concurrent_index_creation.test` appears unrelated to my changes. It also occurred in CI runs for other PRs [here](https://github.com/duckdb/duckdb/actions/runs/12653243840/job/35258013677) and [here](https://github.com/duckdb/duckdb/actions/runs/12655692083/job/35266581283).

2025-01-08 08:16 UTC, lnkuiper commented
Hi again, @thalassemia 

Thanks for the changes! The code looks great now.

I'm glad you added some tests to check the CSV behavior; this was definitely needed. I'm not sure about the issues you encountered there, so I will have to check with our CSV expert @pdet

2025-01-08 11:42 UTC, pdet commented on src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
> +		if (no_cache_union) {
Is this still failing? 
Failures with `PRAGMA enable_verification` for when adding new options are usually related to plan serialization/deserialization, but I see you added this option correctly to `nodes.json` and generated `serialize_nodes.cpp`

2025-01-08 11:55 UTC, pdet commented on src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
> +			types = result.return_types;
You probably want to check if this is a single-file reader before setting names and types

2025-01-08 11:56 UTC, pdet commented on test/sql/copy/csv/glob/test_unmatch_globs.test
> +5	tim	tim@email.com
This should be resolved in the `SchemaDiscovery` of `src/function/table/read_csv.cpp`, I imagine this might be related to the change in `src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp`

2025-01-08 18:51 UTC, thalassemia commented on src/execution/operator/csv_scanner/sniffer/csv_sniffer.cpp
> +		if (no_cache_union) {
It seems to pass for me locally now. I must not have recompiled with the serialization/deserialization updates the last time I tested this. Thanks!

2025-01-08 18:53 UTC, thalassemia commented on src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp
> +			types = result.return_types;
Is the `bind_data.files.size() > 1` in the `if` clause on line 124 sufficient? Also, just out of curiosity, why does the behavior change if this is a single-file reader?

2025-01-08 19:53 UTC, thalassemia commented on test/sql/copy/csv/glob/test_unmatch_globs.test
> +5	tim	tim@email.com
It's definitely related to my change in `src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp` because reverting that causes it to work again. I'm just confused about why this is expected to work when the files do have the schema mismatch mentioned in the error.

Notably, `FROM 'data/csv/glob_dif_dialect/f_*.csv' order by all` yields the same error using the latest release (`v1.1.3 19864453f7`).

2025-01-25 06:23 UTC, thalassemia commented on test/sql/copy/csv/glob/read_csv_glob.test
> +select typeof(#1),typeof(#2),typeof(#3),typeof(#4),typeof(#5) FROM read_csv(['data/csv/per_thread/c2.csv', 'data/csv/per_thread/c1.csv', 'data/csv/per_thread/c3.csv'], union_by_name=true) limit 1
[The documentation](https://duckdb.org/docs/data/multiple_files/combining_schemas.html#combining-schemas) states:

> DuckDB reads the schema of the first file provided, and then unifies columns in subsequent files by column position. This works correctly as long as all files have the same schema. If the schema of the files differs, you might want to use the union_by_name option to allow DuckDB to construct the schema by reading all of the names instead.

Because of #15701, the sniffer determines the schema of the first file (`data/csv/per_thread/c2.csv`) to be five `BOOLEAN` columns. Since the subsequent files do not match this schema, I think it makes sense for `union_by_name` to be required here. My change to `src/execution/operator/csv_scanner/table_function/csv_file_scanner.cpp` exposes this along with the failure in `test/sql/copy/csv/glob/test_unmatch_globs.test`.

2025-08-08 09:29 UTC, closed without merging