feat: add http_proxy setting
duckdb/duckdb pull request #4741
Opened 2022-09-17 13:36 UTC by Mause

Fixes #3836

2022-09-17 16:58 UTC, Mause commented
Looks like I forgot to commit the tests, oops. I'll look at adding support for using the proxy with the httpfs extension next week, though I'll need some direction on how exactly to implement that

2022-09-23 09:44 UTC, Mause commented
@samansmink I'm still working on the final test we discussed, but if you have time to look over the code as it stands that would be greatly appreciated 😁

2022-09-23 13:48 UTC, samansmink reviewed
LGTM! added 1 very nitpicky comment

2022-09-23 13:48 UTC, samansmink commented on src/main/settings/settings.cpp
> +static shared_ptr<ProxyUri> SetHttpProxy(DBConfig &config, const string &url) {
nit: maybe add fancy comment header like others have too

2022-09-29 14:23 UTC, samansmink requested changes
hey @mausse looks good! 

I do have one remark on the way the tests are run currently though. In duckdb we try to keep our tests written in SQL as much as possible. Im wondering if we can do the same here. This would require moving the testing part of the code that currently resides in the `scripts/test_http_proxy_setting.py` file to sqllogictests in the `test` dir.

I understand this is a bit tricky because we need the proxy server, but I think we can make it work using a similar setup to how we currently test s3fs/httpfs, with a script to run a testing http server + proxy, which needs to be launched before running the sqllogictests. For the extension loading this will require some trickery, but we can make use of the fact that we already build a loadable exension to `test/extension/loadable_extension_demo.duckdb_extension`. We can maybe setup a proxy to serve this file on the `bucket.s3.amazonaws.com` domain and have a test that looks similar to `test/extension/install_extension.test_slow`

2023-02-08 10:25 UTC, closed without merging

2023-11-17 12:32 UTC, p3t3rix commented
Is there a different PR that implements this or was the rewrite of the testcases the reason this was closed ?

2023-11-17 13:52 UTC, Mause commented
There's not another pr no. I ran into various issues with the tests so put the work aside, anyone else is welcome to implement the feature if they wish