noswizzle
duckdb/duckdb pull request #4923
Opened 2022-10-08 20:24 UTC by jkub

This does three things:
- narrows the interface to SwizzleablePointer
- Adds one level of type indirection (ArtPointer)
- Adds some comments to SwizzleablePointer implementation

Combined, these make it easier to experiment with and maintain alternate implementations of this pointer type.

2022-10-08 20:58 UTC, Tishj commented
LGTM
I like the separation between SwizzleablePointer and ARTPointer, the extra asserts and comments are valid.
I'm not entirely sure about `empty` in this context, as it doesn't make sense for a pointer to be empty, maybe `valid` would be a better word, then `!pointer.empty()` can turn into `pointer.valid()`

Also slight nitpick: maybe `ARTPointer` over `ArtPointer` ?

2022-10-10 11:22 UTC, pdet requested changes
Hi @jkub thanks for your contribution!

I have some small requests.

In additions to the ones I inlined in the code, I think generally speaking comments like
"This assumes" should be replaced with assertions that check these assumptions. This is generally more helpful because if something breaks it becomes immediately obvious where/why.

2022-10-10 11:22 UTC, pdet commented on src/execution/index/art/swizzleable_pointer.cpp
> +	// Note: If the object already has a non-swizzled pointer, this will leak memory.
Maybe add an assertion here?

2022-10-10 11:22 UTC, pdet commented on src/execution/index/art/swizzleable_pointer.cpp
> +	// operation.
I don't think we use `Note: ` in our comments, just have the comment itself.

2022-10-10 20:31 UTC, jkub commented
@Tishj : What about implementing "operator bool" rather than valid(), to follow standard C++ pointer idioms?

2022-10-11 19:55 UTC, jkub commented
I don't know why "Tidy Check (pull_request)" is failing to find the ARTPointer definition. The compiler doesn't seem to have an issue.

2022-10-13 06:29 UTC, merged

2022-10-13 06:29 UTC, Mytherin commented
Thanks!