Correctly handle NULL values in compound ART keys
duckdb/duckdb pull request #5010
Opened 2022-10-17 13:30 UTC by taniabogatsch

The current implementation of the `CREATE INDEX` operator does not handle `NULL` values in non-first columns of compound ART keys correctly. With this fix, we add another `PhysicalFilter` operator to the pipeline, which filters on 'IS NOT NULL' for each key column.

I also removed the check for `IsPrimary()`, which can never be true in the `CREATE INDEX` statement.

2022-10-21 07:42 UTC, Mytherin commented
@lnkuiper can this be merged?

2022-10-21 08:28 UTC, lnkuiper requested changes
I have one comment, then I think it's good to go:

2022-10-21 08:28 UTC, lnkuiper commented on src/common/types/data_chunk.cpp
> +		D_ASSERT(chunk.ColumnCount() <= ColumnCount());
this seems like debugging code, can we remove this?

2022-10-22 06:33 UTC, merged

2022-10-22 06:33 UTC, Mytherin commented
Thanks!