Default NULL handing for CARDINALITY function
duckdb/duckdb pull request #5073
Opened 2022-10-24 12:03 UTC by lokax

#5072

2022-10-25 09:04 UTC, pdet commented on src/function/scalar/map/cardinality.cpp
> +		throw BinderException("Cardinality must have exactly one arguments");
should arguments be singular?

2022-10-25 09:04 UTC, pdet requested changes
Many thanks for the PR!

Could you add a test with a mix of valid and invalid maps?

2022-10-27 02:38 UTC, lokax commented on src/function/scalar/map/cardinality.cpp
> +		throw BinderException("Cardinality must have exactly one arguments");
The function uses only one argument

2022-11-03 15:37 UTC, merged

2022-11-03 15:37 UTC, Mytherin commented
Thanks!