[Python] Fix support for UInt64 and similar
duckdb/duckdb pull request #5299
Opened 2022-11-11 10:29 UTC by Tishj

This PR fixes #5296 

We had previously added support for consuming these datatypes, but somehow messed something up during testing, I've added extra verification to check that we do actually consume these types properly now.

2022-11-11 11:01 UTC, Mause requested changes

2022-11-11 11:01 UTC, Mause commented on tools/pythonpkg/tests/fast/pandas/test_pandas_types.py
> +            data[chr(ord("a")+i)] = base_df.a.astype(dtype)
Could just do `for letter, dtype in zip(string.alphabet, ...)` here

2022-11-11 23:42 UTC, Tishj commented
Numpy *had* these numeric types, but removed them, and my tests are triggering some weird deprecation error
related to: https://numpy.org/devdocs/release/1.20.0-notes.html#further-numeric-style-types-deprecated

2022-11-12 06:43 UTC, merged

2022-11-12 06:43 UTC, Mytherin commented
Thanks!