httpfs: check environment vars for AWS Credentials
duckdb/duckdb pull request #5419
Opened 2022-11-20 11:46 UTC by satotake

- Read and set AWS environment variables when `httpfs` extension is loaded
    - AWS_DEFAULT_REGION 
    - AWS_ACCESS_KEY_ID 
    - AWS_SECRET_ACCESS_KEY 
    - AWS_SESSION_TOKEN
- issue #4021

2022-11-21 08:18 UTC, mskyttner commented
Nice functionality! 

This might be more of a "discussion" but I wonder about supported or intended usage when changing source during say a CLI session, when using multiple S3 sources (see [#4337](https://github.com/duckdb/duckdb/discussions/4460)) in a session or query? 

I guess one could say that I wonder about usage when "reading and setting environment variables after the extension has been loaded". Will it be possible to change environment variables and point to another httpfs S3 source during a session or is the config read and set only once at "load time" when the extension is loaded at "session startup"?

Zooming out a little, some of the extensions (for example httpfs, postgres with the libpq connection string, maybe more?) require credentials to be provided, and this is the first one to support credentials to be picked up from environment variables. 

Am I right in assuming that credentials are generally expected to "remain the same" throughout a session, even while #4608 allows fetching data from different object storage servers or buckets with different credentials in a single query (when explicitly given in the S3 uri)? 

Related to https://github.com/duckdb/duckdb/discussions/4460#discussioncomment-3637142 - would "reloading" the environment variables to point to another source cause earlier defined views using "previous credentials" to stop working?

2022-11-21 10:17 UTC, alexey-milovidov commented
Does it support the AWS_PROFILE environment variable?

2022-11-21 15:23 UTC, satotake commented
@alexey-milovidov 

> Does it support the AWS_PROFILE environment variable?

Not yet. This is a pretty small improvement, intentionally.

> I guess one could say that I wonder about usage when "reading and setting environment variables after the extension has been loaded". Will it be possible to change environment variables and point to another httpfs S3 source during a session or is the config read and set only once at "load time" when the extension is loaded at "session startup"?

This patch just sets `s3_access_key_id` and etc from env vars on cli starts. So you can (re)set during a session with 

```
SET s3_access_key_id=<your_key>
...
```
as [docs says](https://duckdb.org/docs/extensions/httpfs).

But it is not re-reading env vars,  so it might be good for us to have a function like `reload_aws_envvars();`

2022-11-21 16:02 UTC, satotake commented
> would "reloading" the environment variables to point to another source cause earlier defined views using "previous credentials" to stop working?

Yes. In my opinion, if it is view, it should stop.
If we would like to configure multi-account bucket access, a profile must be paired with a bucket. 
In those cases, the combination qualified url and getenv might be nice.
Anyway, this PR is far simpler.

2022-11-23 19:24 UTC, samansmink requested changes
one small comment, the rest LGTM!

2022-11-23 19:24 UTC, samansmink commented on extension/httpfs/s3fs.cpp
> +		this->config.options.set_variables[key] = Value(evar);
Can we use `DBConfig::SetOption` here?

2022-12-01 10:27 UTC, Mytherin commented
Thanks for the fixes! Looks good - could you just merge with the feature branch so the CI can re-run? We had some issues with the feature branch in the last few days.

2022-12-02 11:33 UTC, satotake commented
I wrongly merged `master` branch (not `feature`). Resetted

2022-12-03 11:27 UTC, merged

2022-12-03 11:27 UTC, Mytherin commented
Thanks! LGTM