[Dev] Clean up of the python pkg folder structure
duckdb/duckdb pull request #5436
Opened 2022-11-21 12:07 UTC by Tishj

This PR allows use of subfolders in the pythonpkg folder, and cleans up some code in there.

Figured I'd make a PR out of this, while I work on #5407 - So no merge conflicts arise as part of these changes.

2022-11-21 14:15 UTC, Mause requested changes

2022-11-21 14:15 UTC, Mause commented on tools/pythonpkg/setup.py
> +        subdir = subdir[dir_len::]
Please use relpath instead of this

Or use glob to replace the entire method maybe?

2022-11-22 01:23 UTC, Mause commented on tools/pythonpkg/setup.py
> +        subdir = subdir[dir_len::]
My main concern is future legibility than anything

2022-11-23 13:50 UTC, Tishj commented
Hmm so clang-tidy is failing because the generated `compile_commands.json` does not contain any commands for the pythonpkg, it gets skipped
Likely because of
```
if(NOT pybind11_FOUND)
  return()
endif()
if(NOT PythonLibs_FOUND)
  return()
endif()
```
Clang-tidy does not throw any helpful error for this though, it just tries to compile the file as is - no includes or anything

2022-11-23 21:34 UTC, Tishj commented
Hmm I'm failing OSX Debug on my fork CI, because it's treating warnings as errors, things I fixed with
<https://github.com/duckdb/duckdb/pull/5436/commits/058249fef8ca4a6f35ebac680db112db035e603f>
But when generating the amalgamation, they still show up?
Seems related to tags/commit hashes - hopefully it's fixed once this is merged

2022-11-30 09:27 UTC, Mytherin commented
Could you merge this with the feature branch again?

2022-12-03 11:26 UTC, merged

2022-12-03 11:26 UTC, Mytherin commented
Thanks! LGTM