[Python] Adding back Query interrupt support (through Ctrl+C)
duckdb/duckdb pull request #5487
Opened 2022-11-24 21:16 UTC by Tishj

This PR fixes functionality we accidentally lost

It also adds a test for this functionality, which I've spent a good few hours on.
Despite that, I could not find a way for this test to fail on master, it just hangs infinitely
it seems `interrupt_main()` gives back control to the main thread, and never gets back control

So I've added a disclaimer to the test, to hopefully aid people that accidentally break this test

2022-11-24 21:22 UTC, Mytherin commented
Thanks for the PR!

> Despite that, I could not find a way for this test to fail on master, it just hangs infinitely


That's fine, we have several tests like that. For example [this test](https://github.com/duckdb/duckdb/blob/master/test/sql/catalog/table/create_table_as_abort.test) that verifies `CREATE TABLE IF NOT EXISTS` short-circuits correctly and does not execute a giant query unnecessarily. Hanging indefinitely means the test would fail the CI, hence that would equal a failure :)

2022-11-25 00:58 UTC, Mause requested changes

2022-11-25 00:58 UTC, Mause commented on tools/pythonpkg/tests/fast/api/test_query_interrupt.py
> +except ImportError:  # for Python 3 compat
We don't support Python 2, so you can remove the first import

2022-11-25 00:58 UTC, Mause commented on tools/pythonpkg/tests/fast/api/test_query_interrupt.py
> +        except RuntimeError:
Please use `pytest.raises` instead

2022-11-28 09:09 UTC, Tishj commented
@Mytherin should I rerun CI on this, I saw 5 were canceled ?

2022-11-28 09:14 UTC, Mytherin commented
> @Mytherin should I rerun CI on this, I saw 5 were canceled ?

I just reran them

2022-11-29 08:36 UTC, Mytherin commented
There are still a lot of cancelled CI runs - I think it is not noise but related to the added test. The cancelled CI are all 6 hour long runs that stop at the exact same moment (https://github.com/duckdb/duckdb/actions/runs/3546245191/jobs/5985938234). The added test likely runs forever.

Perhaps we should just remove the test? Alternatively we can look into fixing it but if this is not easily reproducible that might be challenging.

2022-11-29 10:02 UTC, Tishj commented
Hmm that would indicate that either the Cntrl+C functionality does not work on Linux, or that the python version on linux does not support triggering this programmatically?

I can also change the query to something that will complete within like a minute, and just try to cancel it before it completes - then it at least wont take hours to tell us that it failed

2022-11-29 15:21 UTC, Tishj commented
I'm confused by this now passing CI?
All I did was change the query to take less time, and check if a RuntimeError was raised (that's what happens when the query is succesfully interrupted) instead of a KeyboardInterrupt (which is what would happen if the query was not interrupted - and thus did not consume the keyboard interrupt exception)

2022-11-29 15:25 UTC, Mytherin commented
Maybe there was something weird happening with using `pytest.raises` in this case? It would not surprise me if that has special handling for keyboard interrupts or something that ends up causing the test to hang incorrectly. This is quite an exotic test setup after all.

2022-11-29 15:32 UTC, merged

2022-11-29 15:32 UTC, Mytherin commented
Either way, let's try merging it for now - if the test breaks we can remove it