[Python] `duckdb.execute()` == `duckdb.default_connection.execute()`
duckdb/duckdb pull request #5650
Opened 2022-12-09 13:19 UTC by Tishj

This PR adds functionality suggested by @Mytherin in #5595 

Now for every method that exists on `DuckDBPyConnection` we can also use `duckdb.<method_name>`, with an optional connection supplied.
If no connection argument is given, the default connection is used.

And the plan is to add the ability to change this `default_connection` saved in the `duckdb` module.

2022-12-10 00:53 UTC, Mause requested changes

2022-12-10 00:53 UTC, Mause commented on tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
> +        connection_methods = dir(con)[27:]
Can you add a filter to the loop instead of this hardcoded slice please?

2022-12-10 00:53 UTC, Mause commented on tools/pythonpkg/tests/fast/api/test_duckdb_connection.py
> +        with pytest.raises(duckdb.Error):
Can you please use a specific subclass here instead?

2022-12-11 22:09 UTC, Tishj commented
Linux 32 bit:
```
[1050/2457] (42%): test/sql/join/inner/test_join_invisible_probe.test_slow      
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
unittest is a Catch v2.13.7 host application.
Run with -? for options

-------------------------------------------------------------------------------
test/sql/join/inner/test_join_invisible_probe.test_slow
-------------------------------------------------------------------------------
/__w/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:178
...............................................................................

/__w/duckdb/duckdb/test/sqlite/test_sqllogictest.cpp:178: FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  std::bad_alloc
```
from my recent experience with linux 32 bit, it sounds like this uses too much memory to run on 32 bit, and needs `require 64bit` ?

2022-12-12 12:38 UTC, Mytherin approved these changes
Thanks for the PR! LGTM

2022-12-14 12:47 UTC, Mytherin commented
Good to go from my side - could you just pull and fix the merge conflicts?

2022-12-15 14:10 UTC, merged