NodeJS replacement scans
duckdb/duckdb pull request #5825
Opened 2023-01-04 16:30 UTC by whscullin

Add support for replacement scans to Database objects.

2023-01-04 16:44 UTC, Mause requested changes
Thanks for this, looks great! Just a couple of comments

2023-01-04 16:44 UTC, Mause commented on tools/nodejs/src/database.cpp
> +	duckdb::Value parameter;
Is there a particular reason you're limiting this to a single parameter?

2023-01-04 17:25 UTC, whscullin commented on tools/nodejs/src/database.cpp
> +		Napi::TypeError::New(env, "Holding it wrong").ThrowAsJavaScriptException();
Heh, sure, that's just the standard error response I copied from elsewhere in the code.

2023-01-04 17:25 UTC, whscullin commented on tools/nodejs/lib/duckdb.d.ts
> +  register_replacement_scan(
I initially did that, but I noticed that all of the other register functions used snake case so I switched for consistency.

2023-01-04 17:26 UTC, whscullin commented on tools/nodejs/lib/duckdb.d.ts
> +    callback?: Callback<void>
Probably, again this is just consistent with the rest of the API.

2023-01-04 18:22 UTC, whscullin commented on tools/nodejs/src/database.cpp
> +		Napi::TypeError::New(env, "Holding it wrong").ThrowAsJavaScriptException();
Updated.

2023-01-05 15:51 UTC, Mause commented on tools/nodejs/src/database.cpp
> +		Napi::TypeError::New(env, "Holding it wrong").ThrowAsJavaScriptException();
I think the error message is less of a standard and more of a leftover joke from the initial prototype of the node bindings, they should probably all be removed

2023-01-05 15:54 UTC, Mause commented on tools/nodejs/lib/duckdb.d.ts
> +  register_replacement_scan(
Yeah, my intention is to update the other to the camel case style and have them all support promises - when I find the time 😅

2023-01-05 15:55 UTC, Mause commented on tools/nodejs/lib/duckdb.d.ts
> +    callback?: Callback<void>
My hope is to have them all support promises to reduce callback hell, and the newer ones already do, so my preference would be to have all the new ones use promises instead

2023-01-05 21:22 UTC, whscullin commented on tools/nodejs/lib/duckdb.d.ts
> +    callback?: Callback<void>
Sure, no problem.

2023-01-05 21:24 UTC, whscullin commented on tools/nodejs/lib/duckdb.d.ts
> +  register_replacement_scan(
Updated.

2023-01-07 19:23 UTC, Mytherin reviewed
Thanks for the PR! LGTM. @Mause could you perhaps take a final look?

2023-01-12 11:28 UTC, merged