[Macro] Remove limitation for types of expressions accepted as named arguments
duckdb/duckdb pull request #5876
Opened 2023-01-10 13:12 UTC by Tishj

This PR fixes #5808 

Seems like an easy fix, I do wonder why this limitation was there, as it did not break any tests.
@lnkuiper do you know why we had this limitation?
If so I'll add some tests for them and just add subquery to the accepted types instead.

2023-01-10 13:32 UTC, lnkuiper requested changes
I don't remember exactly why I added this limitation. I think it's because you can make some really weird macros if you allow expressions there. Can you try to create a few more tests? For example:
```sql
-- default param references positional param
create macro my_macro1(a, b := a) as a + b;
-- default param references column of table within subquery expression
create macro my_macro2(a := i) as (select min(a) from integers);
```

These are just two tests that come to mind, but maybe there are more weird default params that you can try.

2023-01-10 13:32 UTC, lnkuiper commented on test/sql/catalog/function/test_macro_default_arg.test
> +#pragma enable_verification;
Does this need to be uncommented again?

2023-01-12 11:59 UTC, Mytherin commented on test/sql/catalog/function/test_macro_default_arg.test
> +#CREATE MACRO f(x := NULL) AS x+1;
Is this meant to be commented out?

2023-01-18 14:48 UTC, Tishj commented
I'm not really sure what type of tests would be needed for this if I'm honest.
I get that removing this limitation is potentially error-prone, especially when we can't figure out why the limitation was there in the first place.
I could just add this type of expression to the whitelist instead of removing the entire limitations altogether, would that be preferable?

2023-01-18 14:50 UTC, Mytherin commented
I think the current solution is fine, @lnkuiper thoughts?

2023-01-18 14:59 UTC, lnkuiper commented
I agree. This can be merged

2023-01-19 11:40 UTC, merged