[python] Use duck typing for arrow dataset
duckdb/duckdb pull request #5998
Opened 2023-01-25 20:50 UTC by changhiskhan

Currently the pyarrow.dataset.Scanner.from_dataset static method is being called to create a scanner which depends on the Arrow C++ Dataset API. This makes it harder to integrate Rust packages using arrow-rs because these use the Arrow C data interface which is very very limited (for stability purposes).

Instead, this is a small PR that uses the Dataset.scanner method to create the Scanner. For regular pyarrow Datasets, that just calls the same Scanner.from_dataset under the hood so there is no difference in behavior. But for Rust-based packages integrated via pyo3, it provides a way to override the behavior and create its own scanner, as long as the final data still meets the RecordBatchReader C data interface.

2023-01-26 09:50 UTC, Mytherin commented
Thanks for the PR! Looks like the CI is not passing - could you have a look?

2023-01-26 10:19 UTC, Mause requested changes

2023-01-26 10:19 UTC, Mause commented on tools/pythonpkg/tests/fast/arrow/test_dataset.py
> +if can_run:
While you're changing this file, can you update it to use pytests importorskip instead?

2023-01-27 01:25 UTC, changhiskhan commented
ok looks like it passed. Thanks @Mause for pointing out importorskip that did the trick.

2023-01-27 13:15 UTC, merged

2023-01-27 13:15 UTC, Mytherin commented
Thanks!