More descriptive error message if we are using a table function as a scalar function
duckdb/duckdb pull request #6201
Opened 2023-02-10 15:59 UTC by Mytherin

This PR improves error messages thrown when using table functions as scalar functions, e.g.:

```sql
SELECT read_csv('test.csv')
```

```sql
Binder Error: Function "read_csv" is a table-function but it is used as a scalar function. This function has to be called a FROM clause (similar to a table).
LINE 1: SELECT read_csv('test.csv')
               ^
```

2023-02-10 16:50 UTC, Mause requested changes

2023-02-10 16:50 UTC, Mause commented on src/planner/binder/expression/bind_function_expression.cpp
> +			    StringUtil::Format("Function \"%s\" is a table-function but it is used as a scalar function. This "
```suggestion
			    StringUtil::Format("Function \"%s\" is a table function but was used as a scalar function. This "
```

2023-02-10 16:50 UTC, Mause commented on src/planner/binder/expression/bind_function_expression.cpp
> +			                       "function has to be called a FROM clause (similar to a table).",
```suggestion
			                       "function has to be called in a FROM clause (similar to a table).",
```

2023-02-11 14:22 UTC, Alex-Monahan commented
These error message fixes are so helpful!! I am sure I will see this message again... Thanks!

2023-02-11 17:53 UTC, merged