Implement predicates in JDBC DB-Meta class
duckdb/duckdb pull request #6866
Opened 2023-03-25 15:17 UTC by pjarra

These are individual commits all referencing #6781.
Support is added for queries to all remaining supports*-predicates in
DuckDBDatabaseMetaData.

2023-03-25 15:27 UTC, Mause requested changes

2023-03-25 15:27 UTC, Mause commented on tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java
> +                throw false;
```suggestion
                return false;
```

2023-03-25 15:27 UTC, Mause commented on tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java
> +                throw true;
```suggestion
                return true;
```

2023-03-25 15:27 UTC, Mause commented on tools/jdbc/src/main/java/org/duckdb/DuckDBDatabaseMetaData.java
> +                throw false;
```suggestion
                return false;
```

2023-03-25 15:45 UTC, pjarra commented
@Mause sorry, fixed these.

2023-03-27 10:58 UTC, merged

2023-03-27 10:58 UTC, Mytherin commented
Thanks!