CSV Rejects table
duckdb/duckdb pull request #7681
Opened 2023-05-25 13:16 UTC by Maxxen

Continuation of #7403

This PR adds the possibility to log rows that failed to be parsed during ingestion when `ignore_errors=true` and the schema is specified into a separate "rejects table" through three new options to the `read_csv` table function
- `rejects_table=<string>` name of a temporary "rejects table" to create
- `rejects_limit=<int>` upper limit of rejects to record to the rejects table
- `rejects_recovery_columns=<varchar[]>` list of column names identifying additional columns whose values will be written to the rejects table for every failing row. Useful for scenarios where you have a "primary key" you know will be clean throughout the CSV that you want to be able to use to identify the cause of ingestion errors. If a recovery column would fail to parse we error out for real as if `ignore_errors=false`.

If the specified `rejects_table` already exists the query will fail, so you can't use the same rejects table multiple times in the same query, and will have to manage its lifetime yourself. However, rejects tables and their metadata are always created as temporary tables/stored in the object cache, and are thus local and bound to the lifetime of the connection.

Example from the tests:
Given the following `example.tsv`
```tsv
alice	10	1	20
bobby	12	2	NOT_A_NUMBER
charlie	7	3	30
```

```sql
SELECT * FROM read_csv(
    'test/sql/copy/csv/data/error/mismatch/example.tsv', 
    sep='\t',
    columns = {'name': 'VARCHAR', 'age': 'INTEGER', 'id': 'INTEGER', 'count': 'INTEGER'}, 
    rejects_table='csv_rejects_table',
    rejects_recovery_columns=['name', 'age'],
    ignore_errors=true
) ORDER BY ALL;
```

|  name   | age | id | count |
|---------|-----|----|-------|
| alice   | 10  | 1  | 20    |
| charlie | 7   | 3  | 30    |

```sql
FROM csv_rejects_table ORDER BY ALL;
```

| line | column | column_name | parsed_value |      recovery_columns      |                        error                         |                       file                        |
|------|--------|-------------|--------------|----------------------------|------------------------------------------------------|---------------------------------------------------|
| 2    | 3      | "count"     | NOT_A_NUMBER | {'name': bobby, 'age': 12} | Could not convert string 'NOT_A_NUMBER' to 'INTEGER' | test/sql/copy/csv/data/error/mismatch/example.tsv |

2023-05-26 09:06 UTC, Maxxen commented
@Mytherin [this CI run](https://github.com/duckdb/duckdb/actions/runs/5082185226/jobs/9138989497?pr=7681) seems like its running into an unrelated segfault (can't see how its affected by this PR), is this known or should I open a new issue?

2023-05-26 09:07 UTC, Mytherin commented
Not a segfault but an assertion trigger :) but yes feel free to open an issue

2023-05-26 10:57 UTC, pdet requested changes
Hi Max, thanks for all the hard work on this. It looks very good, I've only added some small comments regarding the code.

Should we also add support for these options on the COPY statement and the read_csv functions from python?

Also, I think you just check for ignore_errors on type casting. Should we check for ignore errors on delimiters as well, IIRC this is done in the add_value function in the `base_csv_reader`


Could you add a couple more tests?
* Tests that trigger all exceptions you have created (e.g., wrong option setup, missing column from recovery_columns.
* Add tests with `READ_CSV_AUTO`
* Add tests that return more errors, at least over vector size.
* Test where there are more errors than the max number of errors we want to store.

2023-05-30 13:25 UTC, Maxxen commented on src/execution/operator/persistent/base_csv_reader.cpp
> +					auto col_name = to_string(col_idx);
This does create the names the same way as in the bind, I.e. `"column0"`, otherwise it uses the provided names (if there are any).

2023-05-30 14:36 UTC, Maxxen commented
god dammint, I merged with master.

2023-06-03 06:33 UTC, Maxxen commented
@Mytherin All green!

2023-06-05 07:40 UTC, Mytherin reviewed
Thanks for the PR! Looks great - some more minor comments:

2023-06-05 08:01 UTC, Maxxen commented on src/execution/operator/persistent/csv_reader_options.cpp
> +		// skip, handled in SetRejectsOptions
Because the order matters, we can't handle the rejects_table option unless `columns` are resolved (either through argument or auto).

2023-06-05 08:49 UTC, Maxxen commented on src/execution/operator/persistent/base_csv_reader.cpp
> +						break;
On second thought, this won't work, if we throw an error the rejects table doesn't get created. (because the transaction aborts?)

2023-06-05 08:53 UTC, Mytherin commented on src/execution/operator/persistent/base_csv_reader.cpp
> +						break;
Hm, yes that is true. Perhaps a reason not to store the rejects table as an actual table?

2023-06-05 09:03 UTC, Maxxen commented on src/execution/operator/persistent/base_csv_reader.cpp
> +						break;
I agree that it makes sense to throw an error and halt execution, but being able to specify the rejects table as a table was an explicit client request.

2023-06-08 13:32 UTC, Maxxen commented
@Mytherin The regression failure is unrelated. This PR has been passing all checks for a while before I merged with feature this morning. Is there anything else blocking this from getting merged?

2023-06-19 12:50 UTC, merged

2023-06-19 12:50 UTC, Mytherin commented
Thanks!

2023-11-15 17:28 UTC, whelanmike commented
Thanks for this great feature. Is it possible to have the following scenario captured in the `rejects_table`. 
### Use Case:
Starting from the data-loading example above, I have added 1 more record that has an invalid 5th field.
This new record gets ignored silently and is not added to the `rejects_table`.

```csv
alice	10	1	20
bobby	12	2	NOT_A_NUMBER
charlie	7	3	30
NEW	0	1	2	3
```