Add union to test_all_types, and arrow and json R/W
duckdb/duckdb pull request #7701
Opened 2023-05-26 14:38 UTC by Mause

This started out adding support to the Python `.description` field for the union data type, but I realised that we didn't have it in the `test_all_types` table function.

 * Added support for R/W in Arrow, specifically as a Sparse Union. Reading Dense Unions will still fail
 * Added read support for Unions in JSON. Write support was already there, so I just followed the existing pattern
 * Corrected a number of locations where the Union tag type was incorrect - a `uint8_t` instead of a `int8_t`
 * Parquet doesn't support unions (see https://issues.apache.org/jira/browse/PARQUET-756)
 * Added support for reading unions into numpy/pandas (as object type)
 * R support was left on the table, I'm not familiar enough with R to do this without guidance
 * Basic Java union read support is there, but only stringly typed - I'll add full support when I added Struct support (soon)

2023-05-30 13:15 UTC, lnkuiper requested changes
Thanks for the PR! I have left some comments about the `JSONTransform` implementation.

I'm also wondering about how other systems map from JSON to UNION. Do you have any idea? Perhaps we're the only system out there that does this. I always thought that reading JSON like this:
```json
{"value": 42}
{"value": [1, 2, 3]}
```
Could be read using `UNION(int INTEGER, int_list INT[])` without having to wrap them in an object with the keys "int" or "int_list".

But now that I see your implementation, I'm not sure what makes the most sense, especially since I'm not a heavy JSON user myself.

2023-05-30 13:15 UTC, lnkuiper commented on extension/json/json_functions/json_transform.cpp
> +		yyjson_val *key, *val;
I would recommend using `yyjson_obj_foreach` here, it makes the loop more readable. There's a few examples in this file.

2023-05-30 13:15 UTC, lnkuiper commented on extension/json/json_functions/json_transform.cpp
> +		if (key == nullptr) {
`key` should not be able to ever be `nullptr` when using `yyjson_obj_foreach`. Perhaps it's worth checking `yyjson_get_len` here to check if it's an empty object before going into the loop

2023-05-30 13:15 UTC, lnkuiper commented on extension/json/json_functions/json_transform.cpp
> +			result.SetValue(i, Value(nullptr));
For setting results to `NULL`, we use `Validity`
```c++
auto &validity = FlatVector::Validity(result);
result.SetInvalid(i);
```

2023-05-30 13:15 UTC, lnkuiper commented on extension/json/json_functions/json_transform.cpp
> +			throw InvalidInputException("Found object containing unknown key instead of union");
Same as before, could you use the new error handling pattern?

2023-05-30 13:15 UTC, lnkuiper commented on extension/json/json_functions/json_transform.cpp
> +	return true;
This should return `success` - whether we were able to transform all values. So this answers your question: Yes! We should use the return value :)

2023-05-30 14:07 UTC, Mytherin reviewed
Thanks for the PR! Looks great.

As this is adding unions to the arrow conversion - could we add some union-specific arrow conversion tests in the Python client? In particular nested unions, unions with lists/structs inside them, unions inside lists/structs, all are not covered yet but could potentially cause problems.

2023-06-14 15:11 UTC, Maxxen approved these changes

2023-06-15 13:36 UTC, Mytherin commented
Thanks for the fixes! Could you just have a look at the merge conflict? The CI failure in `test/sql/json/test_json_copy.test_slow` also seems related to the changes made in this PR.

2023-06-19 14:39 UTC, Mytherin commented
Could you have a look at the failing CI?

2023-07-07 04:52 UTC, Mause commented
Failures don't look related my changes?

2023-07-07 08:46 UTC, Mytherin commented
Could you merge with master?

2023-07-12 09:04 UTC, merged