Issue #7879: Missing JDBC TIMESTAMP_TZ
duckdb/duckdb pull request #7922
Opened 2023-06-12 19:42 UTC by hawkfish

Add some cases where converting TIMESTAMP_TZ is generating unparseable strings instead of just doing what TIMESTAMP does.

Unsure on how to test this, so suggestions from Java nerds welcome! It did fix a problem I found in Tableau.

2023-06-13 07:23 UTC, Mause requested changes
> Unsure on how to test this, so suggestions from Java nerds welcome!

Something like this maybe?

```java
Statement rs = statement.executeQuery("SELECT now():: TIMEZONE_TZ");
rs.next();
rs.getObject(1, Long.class);
```

2023-06-13 07:23 UTC, Mause commented on tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
> +		rs.getTimestamp(2);
We should probably keep this test as one that tests for the exception? So maybe switch to another data type (bool maybe?)

2023-06-13 07:23 UTC, Mause commented on tools/jdbc/src/main/java/org/duckdb/DuckDBResultSet.java
> +					|| sqlType == DuckDBColumnType.TIMESTAMP
Might be worth pulling out these sets of comparisons? `isTimestampType`, `isLongType`, etc

2023-06-15 16:09 UTC, merged

2023-06-15 16:09 UTC, Mytherin commented
Thanks!