Multiple assignment for `UPDATE SET`
duckdb/duckdb pull request #7968
Opened 2023-06-16 13:54 UTC by nickgerrets

Solves #7069 

Implemented Transform for the `T_MultiAssignRef` expression type.

A ParserException is thrown when the left side of the assignment doesn't have an equal amount of columns as the right side of the assignent, i.e:
`UPDATE tbl SET (a, b, c) = (1, 2);`

2023-06-16 14:16 UTC, Tishj requested changes
Thanks for the PR, the changes here look great, I just had some requests for more tests and improving some error messages.

2023-06-16 14:16 UTC, Tishj commented on test/sql/update/test_multiple_assignment.test
> +
Can we add a test with empty lists?
such as:
`() = (1, 2)`
`(1,2) = ()`

2023-06-16 14:16 UTC, Tishj commented on src/parser/transform/expression/transform_multi_assign_reference.cpp
> +			throw ParserException("Too few columns for Multiple Assignment");
Can we provide a more insightful error message here?
"Could not perform multiple assignment, target expects %d values, only %d were provided"

2023-06-16 14:16 UTC, Tishj commented on src/parser/transform/expression/transform_multi_assign_reference.cpp
> +			throw ParserException("Too many columns for Multiple Assignment");
Can this be more insightful as well, maybe something like:
"Could not perform multiple assignment, expected only %d values, found %d instead"

2023-06-16 14:16 UTC, Tishj commented on src/parser/transform/expression/transform_multi_assign_reference.cpp
> +		return TransformExpression(reinterpret_cast<duckdb_libpgquery::PGNode *>(list->data.ptr_value));
Unrelated comment:
Without looking at the grammar this is super confusing, as I would expect `MultiAssignRef` to contain the full list of assignments: `(a, b, c) = (1,2,3)` but instead we create a `MultiAssignRef` node for every value in the left hand side: `a`, `b` and `c`

2023-06-20 09:05 UTC, Tishj approved these changes
Thanks for the changes!

2023-06-20 09:42 UTC, merged

2023-06-20 09:42 UTC, Mytherin commented
Thanks! Looks great!