Issue #8119: TO_TIMESTAMP Returns TIMESTAMP
duckdb/duckdb pull request #8127
Opened 2023-07-02 12:38 UTC by hawkfish

Switch the signature to DOUBLE => TIMESTAMPTZ to match Postgres.

2023-07-02 13:46 UTC, Mause requested changes

2023-07-02 13:46 UTC, Mause commented on src/include/duckdb/core_functions/scalar/date_functions.hpp
> -	static constexpr const char *Example = "to_timestamp(701222400)";
See line 8 - `// This file is generated by scripts/generate_functions.py` - these changes need to be made in the associated JSON files as well

See https://github.com/duckdb/duckdb/blob/a83afa7cc3d351afd9793a3b01df0a62f05e988b/src/core_functions/scalar/date/functions.json#L360

2023-07-04 08:32 UTC, Mytherin reviewed
Thanks for the PR! LGTM - could we also add some tests that use the new double signature with fractional parts and verify that it works as intended?

2023-07-06 07:49 UTC, merged

2023-07-06 07:50 UTC, Mytherin commented
Thanks! Looks great