Check for duplicate member tag names in serialization generation
duckdb/duckdb pull request #8449
Opened 2023-08-02 12:39 UTC by Maxxen

Also adjust some tag names to no longer conflict within their inheritance chain.

Closes #8381

2023-08-02 12:44 UTC, Mause requested changes

2023-08-02 12:44 UTC, Mause commented on scripts/generate_serialization.py
> +def detect_duplicate_member_names(class_entry):
This function doesn't do anything?

2023-08-02 12:44 UTC, Mause commented on scripts/generate_serialization.py
> +            def traverse_children(node, parents: list, seen: set):
Move this function out of the loop so it doesn't get defined (again) on each iteration?

2023-08-02 13:31 UTC, Maxxen commented on scripts/generate_serialization.py
> +def detect_duplicate_member_names(class_entry):
Ah crap, was going to remove this

2023-08-03 08:07 UTC, Mytherin commented
Thanks! Looks great

2023-08-03 08:07 UTC, merged