[ADBC] Add support for windows.
duckdb/duckdb pull request #9357
Opened 2023-10-16 08:39 UTC by pdet

This pull request introduces the dllexport/import attributes to the adbc_init function.

 It also includes adaptations to the CI process, enabling the execution of ADBC tests on both the Windows and Python-Windows CIs. 

Some adjustments were made to the CPP tests, primarily involving path creation for test databases and connection initialization.

2023-10-16 09:25 UTC, Mause requested changes

2023-10-16 09:25 UTC, Mause commented on .github/workflows/Windows.yml
>        shell: bash
Shouldn't this be PowerShell now?

2023-12-04 10:11 UTC, pdet commented
@Mytherin Is this good to go?

2023-12-06 15:14 UTC, merged

2023-12-06 15:14 UTC, Mytherin commented
Thanks!