JDBC - Appender for Decimal
duckdb/duckdb pull request #9568
Opened 2023-11-04 23:54 UTC by Jens-H

This PR adds the appendBigDecimal method to directly insert BigDecimal into a Decimal column.

Everything down to JNI is touched, but basically the same conversion logic (BigDecimal -> Value::DECIMAL) from SQL insert is used.

A test is included.

2023-11-05 14:11 UTC, Mause requested changes

2023-11-05 14:11 UTC, Mause commented on tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
> +        BigDecimal bd16 = new BigDecimal("12.34").setScale(2);
Can you break this test up a bit? And use slightly more comprehensible variable names?

2023-11-07 22:57 UTC, Jens-H commented on tools/jdbc/src/jni/duckdb_java.cpp
> +	jint precision = env->CallIntMethod(value, J_Decimal_precision);
yeah, good idea
see https://github.com/duckdb/duckdb/pull/9568/commits/cadca20efee821a661816f29f2c03622fff5e16c

2023-11-07 22:58 UTC, Jens-H commented on tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java
> +            exceptionRaised = true;
see https://github.com/duckdb/duckdb/pull/9568/commits/82ae1ac7b744c708bc0f1be1a60cf5ce6f56414a

2023-11-18 20:16 UTC, Jens-H commented
@Mause: How to proceed here?

2023-12-12 12:14 UTC, Mytherin commented
@Mause can this be merged?

2023-12-12 12:43 UTC, Mause approved these changes

2023-12-12 12:44 UTC, merged