Fix: string to integer cast
duckdb/duckdb pull request #9581
Opened 2023-11-06 13:34 UTC by nickgerrets

Solves https://github.com/duckdb/duckdb/issues/5328

This PR adds better support for casting from string to integers (including `HUGEINT`) when exponents and/or decimals are involved.

Examples:
`'1.234e3'::INTEGER` was previously evaluated to `1000` and is now evaluated to `1234`.
`'125e-1'::INTEGER` was previously evaluated to `12` and is now evaluated to `13`.
`'150e-1'::TINYINT` was previously considered a Conversion Error and is now evaluated to `15`.

2023-11-16 08:47 UTC, Tishj commented on src/common/operator/cast_operators.cpp
> +		while (state.decimal > 10) {
We can do a single modulo 10 instead right?

2023-11-16 09:02 UTC, Tishj commented
I tried
```sql
select '0.000005'::INTEGER
```
Which gave me `1`
I'm not sure that's correct?

2023-11-16 09:10 UTC, Tishj commented
As a follow up, this isn't an easy question to answer, but since you're working on this I figured I'd ask you.

Out of these rounding modes, which one does DuckDB follow?
```
rounding ['TIE_TO_EVEN', 'TIE_AWAY_FROM_ZERO', 'TRUNCATE', 'CEILING', 'FLOOR']
```
I think `TIE_AWAY_FROM_ZERO` right?
That seems to be the current behavior, and what I've seen from reviewing this code, decimal `>= 5` is how we determine if we should round up.

2023-11-22 11:30 UTC, nickgerrets commented
> Out of these rounding modes, which one does DuckDB follow?

@Tishj  `TIE_AWAY_FROM_ZERO` is indeed the intended behaviour.

2023-11-28 15:28 UTC, Tishj commented on test/sql/cast/string_to_integer_exponent_cast.test
> +# group: [cast]
I thought of another test where we create the minimal/max value and prefix it with `0.000...`, then construct the exponent to restore the value from the fraction

But that seemed to trigger an assertion
```sql
D select '0.170141183460469231731687303715884105727e39'::HUGEINT;
┌─────────────────────────────────────────────────────────────────┐
│ CAST('0.170141183460469231731687303715884105727e39' AS HUGEINT) │
│                             int128                              │
├─────────────────────────────────────────────────────────────────┤
│                         170141183460469231731687303715884105727 │
└─────────────────────────────────────────────────────────────────┘
D select '0.0170141183460469231731687303715884105727e40'::HUGEINT;
Error: INTERNAL Error: Assertion triggered in file "/Users/thijs/DuckDBLabs/duckdb/src/common/types/hugeint.cpp" on line 314: !(rhs.upper == 0 && rhs.lower == 0)
```

2023-11-28 15:29 UTC, Tishj requested changes
Found a crash that should be fixed and I've requested a couple more tests

2023-12-01 10:06 UTC, Tishj approved these changes
Thanks I think this is ready to be merged now 👍

2023-12-04 13:33 UTC, Mytherin reviewed
Thanks for the PR! Looks good - some more comments:

2023-12-04 13:33 UTC, Mytherin commented on src/common/operator/cast_operators.cpp
> +			while (e++ < 0) {
Can we do an early-out when `state.result==0`

2023-12-04 13:33 UTC, Mytherin commented on src/common/operator/cast_operators.cpp
> +		if (state.decimal == 0) {
Can we add tests:

```sql
select '15123456789e-2147483648'::int;
select '0e2147483647'::int;
```

2023-12-04 13:33 UTC, Mytherin commented on src/common/operator/cast_operators.cpp
> +				power *= 10;
What if power goes out of bounds here, can we check this?

2023-12-04 13:33 UTC, Mytherin commented on src/common/operator/cast_operators.cpp
> +	static bool HandleExponent(T &state, int32_t exponent) {
Can we make exponents a `int16_t`?

2023-12-07 16:59 UTC, merged

2023-12-07 16:59 UTC, Mytherin commented
Thanks!